name: Run Windows Bot

env:
  TOKEN: ${{ secrets.TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD_IDLE_MMO: ${{ secrets.PASSWORD_IDLE_MMO }}

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 */2 * * *'  # Runs every 22 hours

jobs:
  run-bot:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chrome and Chrome Driver
      run: |
        choco install googlechrome -y
        choco install chromedriver -y 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install seleniumbase
        pip install requests

    - name: Run python script
      run: |
        python examples/my_examples/idle_mmo.py --browser=chrome
